name: marketpulse_dbt

profile: marketpulse

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  marketpulse_dbt:
    +static_analysis: strict

    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table